class TestGitClient:
    def test_validate(self) -> None:
        """Test that git repo validation checks work"""

    def test_add(self) -> None: ...

    def test_commit(self) -> None: ...

    def test_pull(self) -> None: ...

    def test_push(self) -> None: ...
